---

- name: configs > Templates
  template:
    src:  "{{ item.template|default(proftpd_configs_template|ternary(proftpd_configs_template, 'configs/empty.j2')) }}"
    dest: "{{ proftpd_configs_dir }}/{{ item.file }}"
  with_items: "{{ proftpd_configs }}"
  notify:
    - proftpd restart

- name: configs > Exclusive - find files
  command: "find -type f -printf '%P\n'"
  args:
    chdir: "{{ proftpd_configs_dir }}"
  changed_when: false
  register: __proftpd_configs_find_output
  when: proftpd_configs_exclusive

- name: configs > Exclusive - remove files
  file:
    path:  "{{ proftpd_configs_dir }}/{{ item }}"
    state: absent
  when: proftpd_configs_exclusive and (item not in proftpd_configs|map(attribute='file'))
  with_items: "{{ __proftpd_configs_find_output.stdout_lines|default([]) }}"
  notify:
    - proftpd restart
