---

- name: users > Template config
  template:
    src:  "{{ proftpd_users_template|ternary(proftpd_users_template, 'users/default.j2') }}"
    dest: "{{ proftpd_users_file }}"
    mode: 0600
  with_items: "{{ proftpd_users }}"
